import { MigrationInterface, QueryRunner } from "typeorm";

export class ValidateFueldsData1752795727820 implements MigrationInterface {
    name = 'ValidateFueldsData1752795727820'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "vehicles" DROP COLUMN "active"`);
        await queryRunner.query(`ALTER TABLE "chassis" DROP COLUMN "date_start"`);
        await queryRunner.query(`ALTER TABLE "chassis" DROP COLUMN "date_end"`);
        await queryRunner.query(`ALTER TABLE "photos" DROP COLUMN "active"`);
        await queryRunner.query(`ALTER TABLE "countries" ADD "created_at" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "UQ_8b0be371d28245da6e4f4b61878" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "categories" ALTER COLUMN "description" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "categories" ALTER COLUMN "active" SET DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "categories" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "categories" ADD "created_at" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD CONSTRAINT "UQ_aa397b791341ed3615397050d4b" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "brands" ADD CONSTRAINT "UQ_96db6bbbaa6f23cad26871339b6" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "brands" ALTER COLUMN "active" SET DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "brands" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "brands" ADD "created_at" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "brands" ALTER COLUMN "logo" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "companies" ADD CONSTRAINT "UQ_3dacbb3eb4f095e29372ff8e131" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "companies" ALTER COLUMN "active" SET DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "photographers" ADD CONSTRAINT "UQ_56c3501b9a9f8bac3bf04088fc1" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "photographers" ADD CONSTRAINT "UQ_eb11643ce7440cd7b40efa11b86" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "photographers" ADD CONSTRAINT "UQ_326173677b395ac71e093ded28c" UNIQUE ("phone")`);
        await queryRunner.query(`ALTER TABLE "photographers" ALTER COLUMN "active" SET DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "countries" ADD CONSTRAINT "UQ_fa1376321185575cf2226b1491d" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "countries" ADD CONSTRAINT "UQ_31d60a54633e88225b40081e187" UNIQUE ("iso_code")`);
        await queryRunner.query(`ALTER TABLE "bodyworks" ALTER COLUMN "active" SET DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "chassis" DROP CONSTRAINT "FK_d5d68b66ef680cd22875325ee35"`);
        await queryRunner.query(`ALTER TABLE "chassis" DROP CONSTRAINT "FK_cbcb9842c0e523c1d479b375860"`);
        await queryRunner.query(`ALTER TABLE "chassis" ADD CONSTRAINT "UQ_d5d68b66ef680cd22875325ee35" UNIQUE ("brand_id")`);
        await queryRunner.query(`ALTER TABLE "chassis" ADD CONSTRAINT "UQ_f425806a8ab503263cdfa87b04b" UNIQUE ("model")`);
        await queryRunner.query(`ALTER TABLE "chassis" ALTER COLUMN "description" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "chassis" ADD CONSTRAINT "UQ_cbcb9842c0e523c1d479b375860" UNIQUE ("vehicle_id")`);
        await queryRunner.query(`ALTER TABLE "chassis" ALTER COLUMN "active" SET DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "chassis" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "chassis" ADD "created_at" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "serials" ADD CONSTRAINT "UQ_1878cd334630a7237b71ad1b51b" UNIQUE ("serial_code")`);
        await queryRunner.query(`ALTER TABLE "serials" ADD CONSTRAINT "UQ_7e069b3eaa4af7a8dc47cd3ccf6" UNIQUE ("company_id")`);
        await queryRunner.query(`ALTER TABLE "photos" DROP CONSTRAINT "FK_f7b47da1a50daa1aafcb27510a9"`);
        await queryRunner.query(`ALTER TABLE "photos" DROP CONSTRAINT "FK_a74f42e665f8fde707f2f6c047b"`);
        await queryRunner.query(`ALTER TABLE "photos" DROP CONSTRAINT "FK_a300a78db7beb39c34894b1c9a3"`);
        await queryRunner.query(`ALTER TABLE "photos" DROP CONSTRAINT "FK_0a12d0edfea632488e30a8f390f"`);
        await queryRunner.query(`ALTER TABLE "photos" DROP CONSTRAINT "FK_d741339e91995df8108659f20a6"`);
        await queryRunner.query(`ALTER TABLE "photos" DROP CONSTRAINT "FK_3811669e6fb07fa931be040623e"`);
        await queryRunner.query(`ALTER TABLE "photos" DROP CONSTRAINT "FK_09cb4018cf31055b1a4a720045f"`);
        await queryRunner.query(`ALTER TABLE "photos" ADD CONSTRAINT "UQ_f7b47da1a50daa1aafcb27510a9" UNIQUE ("vehicle_id")`);
        await queryRunner.query(`ALTER TABLE "photos" ADD CONSTRAINT "UQ_d5bfcd886a99a4d2c3db9c11e45" UNIQUE ("image_url")`);
        await queryRunner.query(`ALTER TABLE "photos" ADD CONSTRAINT "UQ_a74f42e665f8fde707f2f6c047b" UNIQUE ("brand_id")`);
        await queryRunner.query(`ALTER TABLE "photos" ADD CONSTRAINT "UQ_a300a78db7beb39c34894b1c9a3" UNIQUE ("company_id")`);
        await queryRunner.query(`ALTER TABLE "photos" ADD CONSTRAINT "UQ_0a12d0edfea632488e30a8f390f" UNIQUE ("chassis_id")`);
        await queryRunner.query(`ALTER TABLE "photos" ADD CONSTRAINT "UQ_d741339e91995df8108659f20a6" UNIQUE ("bodywork_id")`);
        await queryRunner.query(`ALTER TABLE "photos" ADD CONSTRAINT "UQ_3811669e6fb07fa931be040623e" UNIQUE ("photographer_id")`);
        await queryRunner.query(`ALTER TABLE "photos" ADD CONSTRAINT "UQ_09cb4018cf31055b1a4a720045f" UNIQUE ("country_id")`);
        await queryRunner.query(`ALTER TABLE "chassis" ADD CONSTRAINT "FK_d5d68b66ef680cd22875325ee35" FOREIGN KEY ("brand_id") REFERENCES "brands"("brand_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chassis" ADD CONSTRAINT "FK_cbcb9842c0e523c1d479b375860" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("vehicle_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "photos" ADD CONSTRAINT "FK_f7b47da1a50daa1aafcb27510a9" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("vehicle_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "photos" ADD CONSTRAINT "FK_a74f42e665f8fde707f2f6c047b" FOREIGN KEY ("brand_id") REFERENCES "brands"("brand_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "photos" ADD CONSTRAINT "FK_0a12d0edfea632488e30a8f390f" FOREIGN KEY ("chassis_id") REFERENCES "chassis"("chassis_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "photos" ADD CONSTRAINT "FK_d741339e91995df8108659f20a6" FOREIGN KEY ("bodywork_id") REFERENCES "bodyworks"("bodywork_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "photos" ADD CONSTRAINT "FK_a300a78db7beb39c34894b1c9a3" FOREIGN KEY ("company_id") REFERENCES "companies"("company_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "photos" ADD CONSTRAINT "FK_3811669e6fb07fa931be040623e" FOREIGN KEY ("photographer_id") REFERENCES "photographers"("photographer_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "photos" ADD CONSTRAINT "FK_09cb4018cf31055b1a4a720045f" FOREIGN KEY ("country_id") REFERENCES "countries"("country_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "photos" DROP CONSTRAINT "FK_09cb4018cf31055b1a4a720045f"`);
        await queryRunner.query(`ALTER TABLE "photos" DROP CONSTRAINT "FK_3811669e6fb07fa931be040623e"`);
        await queryRunner.query(`ALTER TABLE "photos" DROP CONSTRAINT "FK_a300a78db7beb39c34894b1c9a3"`);
        await queryRunner.query(`ALTER TABLE "photos" DROP CONSTRAINT "FK_d741339e91995df8108659f20a6"`);
        await queryRunner.query(`ALTER TABLE "photos" DROP CONSTRAINT "FK_0a12d0edfea632488e30a8f390f"`);
        await queryRunner.query(`ALTER TABLE "photos" DROP CONSTRAINT "FK_a74f42e665f8fde707f2f6c047b"`);
        await queryRunner.query(`ALTER TABLE "photos" DROP CONSTRAINT "FK_f7b47da1a50daa1aafcb27510a9"`);
        await queryRunner.query(`ALTER TABLE "chassis" DROP CONSTRAINT "FK_cbcb9842c0e523c1d479b375860"`);
        await queryRunner.query(`ALTER TABLE "chassis" DROP CONSTRAINT "FK_d5d68b66ef680cd22875325ee35"`);
        await queryRunner.query(`ALTER TABLE "photos" DROP CONSTRAINT "UQ_09cb4018cf31055b1a4a720045f"`);
        await queryRunner.query(`ALTER TABLE "photos" DROP CONSTRAINT "UQ_3811669e6fb07fa931be040623e"`);
        await queryRunner.query(`ALTER TABLE "photos" DROP CONSTRAINT "UQ_d741339e91995df8108659f20a6"`);
        await queryRunner.query(`ALTER TABLE "photos" DROP CONSTRAINT "UQ_0a12d0edfea632488e30a8f390f"`);
        await queryRunner.query(`ALTER TABLE "photos" DROP CONSTRAINT "UQ_a300a78db7beb39c34894b1c9a3"`);
        await queryRunner.query(`ALTER TABLE "photos" DROP CONSTRAINT "UQ_a74f42e665f8fde707f2f6c047b"`);
        await queryRunner.query(`ALTER TABLE "photos" DROP CONSTRAINT "UQ_d5bfcd886a99a4d2c3db9c11e45"`);
        await queryRunner.query(`ALTER TABLE "photos" DROP CONSTRAINT "UQ_f7b47da1a50daa1aafcb27510a9"`);
        await queryRunner.query(`ALTER TABLE "photos" ADD CONSTRAINT "FK_09cb4018cf31055b1a4a720045f" FOREIGN KEY ("country_id") REFERENCES "countries"("country_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "photos" ADD CONSTRAINT "FK_3811669e6fb07fa931be040623e" FOREIGN KEY ("photographer_id") REFERENCES "photographers"("photographer_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "photos" ADD CONSTRAINT "FK_d741339e91995df8108659f20a6" FOREIGN KEY ("bodywork_id") REFERENCES "bodyworks"("bodywork_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "photos" ADD CONSTRAINT "FK_0a12d0edfea632488e30a8f390f" FOREIGN KEY ("chassis_id") REFERENCES "chassis"("chassis_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "photos" ADD CONSTRAINT "FK_a300a78db7beb39c34894b1c9a3" FOREIGN KEY ("company_id") REFERENCES "companies"("company_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "photos" ADD CONSTRAINT "FK_a74f42e665f8fde707f2f6c047b" FOREIGN KEY ("brand_id") REFERENCES "brands"("brand_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "photos" ADD CONSTRAINT "FK_f7b47da1a50daa1aafcb27510a9" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("vehicle_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "serials" DROP CONSTRAINT "UQ_7e069b3eaa4af7a8dc47cd3ccf6"`);
        await queryRunner.query(`ALTER TABLE "serials" DROP CONSTRAINT "UQ_1878cd334630a7237b71ad1b51b"`);
        await queryRunner.query(`ALTER TABLE "chassis" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "chassis" ADD "created_at" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "chassis" ALTER COLUMN "active" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "chassis" DROP CONSTRAINT "UQ_cbcb9842c0e523c1d479b375860"`);
        await queryRunner.query(`ALTER TABLE "chassis" ALTER COLUMN "description" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "chassis" DROP CONSTRAINT "UQ_f425806a8ab503263cdfa87b04b"`);
        await queryRunner.query(`ALTER TABLE "chassis" DROP CONSTRAINT "UQ_d5d68b66ef680cd22875325ee35"`);
        await queryRunner.query(`ALTER TABLE "chassis" ADD CONSTRAINT "FK_cbcb9842c0e523c1d479b375860" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("vehicle_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chassis" ADD CONSTRAINT "FK_d5d68b66ef680cd22875325ee35" FOREIGN KEY ("brand_id") REFERENCES "brands"("brand_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bodyworks" ALTER COLUMN "active" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "countries" DROP CONSTRAINT "UQ_31d60a54633e88225b40081e187"`);
        await queryRunner.query(`ALTER TABLE "countries" DROP CONSTRAINT "UQ_fa1376321185575cf2226b1491d"`);
        await queryRunner.query(`ALTER TABLE "photographers" ALTER COLUMN "active" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "photographers" DROP CONSTRAINT "UQ_326173677b395ac71e093ded28c"`);
        await queryRunner.query(`ALTER TABLE "photographers" DROP CONSTRAINT "UQ_eb11643ce7440cd7b40efa11b86"`);
        await queryRunner.query(`ALTER TABLE "photographers" DROP CONSTRAINT "UQ_56c3501b9a9f8bac3bf04088fc1"`);
        await queryRunner.query(`ALTER TABLE "companies" ALTER COLUMN "active" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "companies" DROP CONSTRAINT "UQ_3dacbb3eb4f095e29372ff8e131"`);
        await queryRunner.query(`ALTER TABLE "brands" ALTER COLUMN "logo" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "brands" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "brands" ADD "created_at" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "brands" ALTER COLUMN "active" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "brands" DROP CONSTRAINT "UQ_96db6bbbaa6f23cad26871339b6"`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP CONSTRAINT "UQ_aa397b791341ed3615397050d4b"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "categories" ADD "created_at" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "categories" ALTER COLUMN "active" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "categories" ALTER COLUMN "description" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "UQ_8b0be371d28245da6e4f4b61878"`);
        await queryRunner.query(`ALTER TABLE "countries" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "photos" ADD "active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "chassis" ADD "date_end" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "chassis" ADD "date_start" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD "active" boolean NOT NULL`);
    }

}
